namespace QLTIEMBANLAPTOP
{
    partial class FNhanVien
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FNhanVien));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.label12 = new System.Windows.Forms.Label();
            this.btXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btADD = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dgvNhanVien = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.panelUpdate = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.btThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtTendanhnhap = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMatKhau = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cboChucVu = new System.Windows.Forms.ComboBox();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSDT = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTenNV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMaNV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.labelUpDate = new System.Windows.Forms.Label();
            this.buttExit = new System.Windows.Forms.Button();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNhanVien)).BeginInit();
            this.panelUpdate.SuspendLayout();
            this.SuspendLayout();
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Segoe UI", 19.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label12.Location = new System.Drawing.Point(573, 9);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(331, 45);
            this.label12.TabIndex = 21;
            this.label12.Text = "Thông tin nhân viên";
            // 
            // btXoa
            // 
            this.btXoa.AllowAnimations = true;
            this.btXoa.AllowMouseEffects = true;
            this.btXoa.AllowToggling = false;
            this.btXoa.AnimationSpeed = 200;
            this.btXoa.AutoGenerateColors = false;
            this.btXoa.AutoRoundBorders = false;
            this.btXoa.AutoSizeLeftIcon = true;
            this.btXoa.AutoSizeRightIcon = true;
            this.btXoa.BackColor = System.Drawing.Color.Transparent;
            this.btXoa.BackColor1 = System.Drawing.Color.Lavender;
            this.btXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btXoa.BackgroundImage")));
            this.btXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btXoa.ButtonText = "xóa";
            this.btXoa.ButtonTextMarginLeft = 0;
            this.btXoa.ColorContrastOnClick = 45;
            this.btXoa.ColorContrastOnHover = 45;
            this.btXoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btXoa.CustomizableEdges = borderEdges1;
            this.btXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btXoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btXoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btXoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btXoa.Font = new System.Drawing.Font("Arial", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btXoa.ForeColor = System.Drawing.Color.BlueViolet;
            this.btXoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btXoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btXoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btXoa.IconMarginLeft = 11;
            this.btXoa.IconPadding = 10;
            this.btXoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btXoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btXoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btXoa.IconSize = 25;
            this.btXoa.IdleBorderColor = System.Drawing.Color.Indigo;
            this.btXoa.IdleBorderRadius = 40;
            this.btXoa.IdleBorderThickness = 1;
            this.btXoa.IdleFillColor = System.Drawing.Color.Lavender;
            this.btXoa.IdleIconLeftImage = null;
            this.btXoa.IdleIconRightImage = null;
            this.btXoa.IndicateFocus = false;
            this.btXoa.Location = new System.Drawing.Point(305, 640);
            this.btXoa.Name = "btXoa";
            this.btXoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btXoa.OnDisabledState.BorderRadius = 40;
            this.btXoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btXoa.OnDisabledState.BorderThickness = 1;
            this.btXoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btXoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btXoa.OnDisabledState.IconLeftImage = null;
            this.btXoa.OnDisabledState.IconRightImage = null;
            this.btXoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btXoa.onHoverState.BorderRadius = 40;
            this.btXoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btXoa.onHoverState.BorderThickness = 1;
            this.btXoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btXoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btXoa.onHoverState.IconLeftImage = null;
            this.btXoa.onHoverState.IconRightImage = null;
            this.btXoa.OnIdleState.BorderColor = System.Drawing.Color.Indigo;
            this.btXoa.OnIdleState.BorderRadius = 40;
            this.btXoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btXoa.OnIdleState.BorderThickness = 1;
            this.btXoa.OnIdleState.FillColor = System.Drawing.Color.Lavender;
            this.btXoa.OnIdleState.ForeColor = System.Drawing.Color.BlueViolet;
            this.btXoa.OnIdleState.IconLeftImage = null;
            this.btXoa.OnIdleState.IconRightImage = null;
            this.btXoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btXoa.OnPressedState.BorderRadius = 40;
            this.btXoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btXoa.OnPressedState.BorderThickness = 1;
            this.btXoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btXoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btXoa.OnPressedState.IconLeftImage = null;
            this.btXoa.OnPressedState.IconRightImage = null;
            this.btXoa.Size = new System.Drawing.Size(138, 39);
            this.btXoa.TabIndex = 34;
            this.btXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btXoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btXoa.TextMarginLeft = 0;
            this.btXoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btXoa.UseDefaultRadiusAndThickness = true;
            this.btXoa.Click += new System.EventHandler(this.btXoa_Click);
            // 
            // btADD
            // 
            this.btADD.AllowAnimations = true;
            this.btADD.AllowMouseEffects = true;
            this.btADD.AllowToggling = false;
            this.btADD.AnimationSpeed = 200;
            this.btADD.AutoGenerateColors = false;
            this.btADD.AutoRoundBorders = false;
            this.btADD.AutoSizeLeftIcon = true;
            this.btADD.AutoSizeRightIcon = true;
            this.btADD.BackColor = System.Drawing.Color.Transparent;
            this.btADD.BackColor1 = System.Drawing.Color.Lavender;
            this.btADD.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btADD.BackgroundImage")));
            this.btADD.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btADD.ButtonText = "Thêm";
            this.btADD.ButtonTextMarginLeft = 0;
            this.btADD.ColorContrastOnClick = 45;
            this.btADD.ColorContrastOnHover = 45;
            this.btADD.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btADD.CustomizableEdges = borderEdges2;
            this.btADD.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btADD.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btADD.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btADD.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btADD.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btADD.Font = new System.Drawing.Font("Arial", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btADD.ForeColor = System.Drawing.Color.BlueViolet;
            this.btADD.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btADD.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btADD.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btADD.IconMarginLeft = 11;
            this.btADD.IconPadding = 10;
            this.btADD.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btADD.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btADD.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btADD.IconSize = 25;
            this.btADD.IdleBorderColor = System.Drawing.Color.Indigo;
            this.btADD.IdleBorderRadius = 40;
            this.btADD.IdleBorderThickness = 1;
            this.btADD.IdleFillColor = System.Drawing.Color.Lavender;
            this.btADD.IdleIconLeftImage = null;
            this.btADD.IdleIconRightImage = null;
            this.btADD.IndicateFocus = false;
            this.btADD.Location = new System.Drawing.Point(47, 107);
            this.btADD.Name = "btADD";
            this.btADD.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btADD.OnDisabledState.BorderRadius = 40;
            this.btADD.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btADD.OnDisabledState.BorderThickness = 1;
            this.btADD.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btADD.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btADD.OnDisabledState.IconLeftImage = null;
            this.btADD.OnDisabledState.IconRightImage = null;
            this.btADD.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btADD.onHoverState.BorderRadius = 40;
            this.btADD.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btADD.onHoverState.BorderThickness = 1;
            this.btADD.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btADD.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btADD.onHoverState.IconLeftImage = null;
            this.btADD.onHoverState.IconRightImage = null;
            this.btADD.OnIdleState.BorderColor = System.Drawing.Color.Indigo;
            this.btADD.OnIdleState.BorderRadius = 40;
            this.btADD.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btADD.OnIdleState.BorderThickness = 1;
            this.btADD.OnIdleState.FillColor = System.Drawing.Color.Lavender;
            this.btADD.OnIdleState.ForeColor = System.Drawing.Color.BlueViolet;
            this.btADD.OnIdleState.IconLeftImage = null;
            this.btADD.OnIdleState.IconRightImage = null;
            this.btADD.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btADD.OnPressedState.BorderRadius = 40;
            this.btADD.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btADD.OnPressedState.BorderThickness = 1;
            this.btADD.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btADD.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btADD.OnPressedState.IconLeftImage = null;
            this.btADD.OnPressedState.IconRightImage = null;
            this.btADD.Size = new System.Drawing.Size(138, 39);
            this.btADD.TabIndex = 35;
            this.btADD.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btADD.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btADD.TextMarginLeft = 0;
            this.btADD.TextPadding = new System.Windows.Forms.Padding(0);
            this.btADD.UseDefaultRadiusAndThickness = true;
            this.btADD.Click += new System.EventHandler(this.btADD_Click);
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Controls.Add(this.bunifuTextBox2);
            this.panel1.Location = new System.Drawing.Point(7, 51);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(414, 50);
            this.panel1.TabIndex = 36;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.LightGray;
            this.pictureBox1.Image = global::QLTIEMBANLAPTOP.Properties.Resources.search;
            this.pictureBox1.Location = new System.Drawing.Point(362, 10);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(38, 30);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 17;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuTextBox2
            // 
            this.bunifuTextBox2.AcceptsReturn = false;
            this.bunifuTextBox2.AcceptsTab = false;
            this.bunifuTextBox2.AnimationSpeed = 200;
            this.bunifuTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox2.BackgroundImage")));
            this.bunifuTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox2.BorderColorIdle = System.Drawing.Color.LightGray;
            this.bunifuTextBox2.BorderRadius = 35;
            this.bunifuTextBox2.BorderThickness = 1;
            this.bunifuTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox2.DefaultText = "";
            this.bunifuTextBox2.FillColor = System.Drawing.Color.LightGray;
            this.bunifuTextBox2.HideSelection = true;
            this.bunifuTextBox2.IconLeft = null;
            this.bunifuTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.IconPadding = 10;
            this.bunifuTextBox2.IconRight = null;
            this.bunifuTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox2.Lines = new string[0];
            this.bunifuTextBox2.Location = new System.Drawing.Point(15, 4);
            this.bunifuTextBox2.MaxLength = 32767;
            this.bunifuTextBox2.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox2.Modified = false;
            this.bunifuTextBox2.Multiline = false;
            this.bunifuTextBox2.Name = "bunifuTextBox2";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox2.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.LightGray;
            stateProperties4.FillColor = System.Drawing.Color.LightGray;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox2.OnIdleState = stateProperties4;
            this.bunifuTextBox2.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox2.PasswordChar = '\0';
            this.bunifuTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox2.PlaceholderText = "Tìm Kiếm";
            this.bunifuTextBox2.ReadOnly = false;
            this.bunifuTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox2.SelectedText = "";
            this.bunifuTextBox2.SelectionLength = 0;
            this.bunifuTextBox2.SelectionStart = 0;
            this.bunifuTextBox2.ShortcutsEnabled = true;
            this.bunifuTextBox2.Size = new System.Drawing.Size(396, 41);
            this.bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox2.TabIndex = 15;
            this.bunifuTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox2.TextMarginBottom = 0;
            this.bunifuTextBox2.TextMarginLeft = 3;
            this.bunifuTextBox2.TextMarginTop = 0;
            this.bunifuTextBox2.TextPlaceholder = "Tìm Kiếm";
            this.bunifuTextBox2.UseSystemPasswordChar = false;
            this.bunifuTextBox2.WordWrap = true;
            this.bunifuTextBox2.TextChanged += new System.EventHandler(this.bunifuTextBox2_TextChanged);
            // 
            // dgvNhanVien
            // 
            this.dgvNhanVien.AllowCustomTheming = true;
            this.dgvNhanVien.AllowUserToAddRows = false;
            this.dgvNhanVien.AllowUserToDeleteRows = false;
            this.dgvNhanVien.AllowUserToResizeColumns = false;
            this.dgvNhanVien.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgvNhanVien.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvNhanVien.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvNhanVien.BackgroundColor = System.Drawing.Color.White;
            this.dgvNhanVien.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvNhanVien.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvNhanVien.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.MediumPurple;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.MediumPurple;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvNhanVien.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvNhanVien.ColumnHeadersHeight = 40;
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Lavender;
            this.dgvNhanVien.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvNhanVien.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvNhanVien.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvNhanVien.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.MediumPurple;
            this.dgvNhanVien.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhanVien.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvNhanVien.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.MediumPurple;
            this.dgvNhanVien.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvNhanVien.CurrentTheme.Name = null;
            this.dgvNhanVien.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvNhanVien.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvNhanVien.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvNhanVien.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.Lavender;
            this.dgvNhanVien.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.Lavender;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvNhanVien.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvNhanVien.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.dgvNhanVien.EnableHeadersVisualStyles = false;
            this.dgvNhanVien.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvNhanVien.HeaderBackColor = System.Drawing.Color.MediumPurple;
            this.dgvNhanVien.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvNhanVien.HeaderForeColor = System.Drawing.Color.White;
            this.dgvNhanVien.Location = new System.Drawing.Point(0, 152);
            this.dgvNhanVien.Name = "dgvNhanVien";
            this.dgvNhanVien.ReadOnly = true;
            this.dgvNhanVien.RowHeadersVisible = false;
            this.dgvNhanVien.RowHeadersWidth = 51;
            this.dgvNhanVien.RowTemplate.Height = 40;
            this.dgvNhanVien.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvNhanVien.Size = new System.Drawing.Size(1389, 618);
            this.dgvNhanVien.TabIndex = 37;
            this.dgvNhanVien.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvNhanVien.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvNhanVien_CellDoubleClick);
            // 
            // panelUpdate
            // 
            this.panelUpdate.BackColor = System.Drawing.Color.Transparent;
            this.panelUpdate.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.panelUpdate.BorderRadius = 1;
            this.panelUpdate.BorderThickness = 1;
            this.panelUpdate.Controls.Add(this.btThem);
            this.panelUpdate.Controls.Add(this.txtTendanhnhap);
            this.panelUpdate.Controls.Add(this.txtMatKhau);
            this.panelUpdate.Controls.Add(this.cboChucVu);
            this.panelUpdate.Controls.Add(this.btXoa);
            this.panelUpdate.Controls.Add(this.bunifuTextBox1);
            this.panelUpdate.Controls.Add(this.txtSDT);
            this.panelUpdate.Controls.Add(this.txtTenNV);
            this.panelUpdate.Controls.Add(this.txtMaNV);
            this.panelUpdate.Controls.Add(this.btUpdate);
            this.panelUpdate.Controls.Add(this.labelUpDate);
            this.panelUpdate.Controls.Add(this.buttExit);
            this.panelUpdate.Controls.Add(this.label3);
            this.panelUpdate.Controls.Add(this.label4);
            this.panelUpdate.Controls.Add(this.label5);
            this.panelUpdate.Controls.Add(this.label7);
            this.panelUpdate.Controls.Add(this.label6);
            this.panelUpdate.Controls.Add(this.label2);
            this.panelUpdate.Dock = System.Windows.Forms.DockStyle.Right;
            this.panelUpdate.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.panelUpdate.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.panelUpdate.Location = new System.Drawing.Point(667, 0);
            this.panelUpdate.Name = "panelUpdate";
            this.panelUpdate.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.panelUpdate.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.panelUpdate.ShadowColor = System.Drawing.Color.DarkGray;
            this.panelUpdate.ShadowDept = 2;
            this.panelUpdate.ShadowDepth = 5;
            this.panelUpdate.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.panelUpdate.ShadowTopLeftVisible = false;
            this.panelUpdate.Size = new System.Drawing.Size(722, 152);
            this.panelUpdate.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.panelUpdate.TabIndex = 38;
            this.panelUpdate.Visible = false;
            // 
            // btThem
            // 
            this.btThem.AllowAnimations = true;
            this.btThem.AllowMouseEffects = true;
            this.btThem.AllowToggling = false;
            this.btThem.AnimationSpeed = 200;
            this.btThem.AutoGenerateColors = false;
            this.btThem.AutoRoundBorders = false;
            this.btThem.AutoSizeLeftIcon = true;
            this.btThem.AutoSizeRightIcon = true;
            this.btThem.BackColor = System.Drawing.Color.Transparent;
            this.btThem.BackColor1 = System.Drawing.Color.Lavender;
            this.btThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btThem.BackgroundImage")));
            this.btThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btThem.ButtonText = "Lưu";
            this.btThem.ButtonTextMarginLeft = 0;
            this.btThem.ColorContrastOnClick = 45;
            this.btThem.ColorContrastOnHover = 45;
            this.btThem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btThem.CustomizableEdges = borderEdges3;
            this.btThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btThem.Font = new System.Drawing.Font("Arial", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btThem.ForeColor = System.Drawing.Color.BlueViolet;
            this.btThem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btThem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btThem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btThem.IconMarginLeft = 11;
            this.btThem.IconPadding = 10;
            this.btThem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btThem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btThem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btThem.IconSize = 25;
            this.btThem.IdleBorderColor = System.Drawing.Color.Indigo;
            this.btThem.IdleBorderRadius = 40;
            this.btThem.IdleBorderThickness = 1;
            this.btThem.IdleFillColor = System.Drawing.Color.Lavender;
            this.btThem.IdleIconLeftImage = null;
            this.btThem.IdleIconRightImage = null;
            this.btThem.IndicateFocus = false;
            this.btThem.Location = new System.Drawing.Point(475, 685);
            this.btThem.Name = "btThem";
            this.btThem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btThem.OnDisabledState.BorderRadius = 40;
            this.btThem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btThem.OnDisabledState.BorderThickness = 1;
            this.btThem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btThem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btThem.OnDisabledState.IconLeftImage = null;
            this.btThem.OnDisabledState.IconRightImage = null;
            this.btThem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btThem.onHoverState.BorderRadius = 40;
            this.btThem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btThem.onHoverState.BorderThickness = 1;
            this.btThem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btThem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btThem.onHoverState.IconLeftImage = null;
            this.btThem.onHoverState.IconRightImage = null;
            this.btThem.OnIdleState.BorderColor = System.Drawing.Color.Indigo;
            this.btThem.OnIdleState.BorderRadius = 40;
            this.btThem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btThem.OnIdleState.BorderThickness = 1;
            this.btThem.OnIdleState.FillColor = System.Drawing.Color.Lavender;
            this.btThem.OnIdleState.ForeColor = System.Drawing.Color.BlueViolet;
            this.btThem.OnIdleState.IconLeftImage = null;
            this.btThem.OnIdleState.IconRightImage = null;
            this.btThem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btThem.OnPressedState.BorderRadius = 40;
            this.btThem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btThem.OnPressedState.BorderThickness = 1;
            this.btThem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btThem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btThem.OnPressedState.IconLeftImage = null;
            this.btThem.OnPressedState.IconRightImage = null;
            this.btThem.Size = new System.Drawing.Size(138, 39);
            this.btThem.TabIndex = 33;
            this.btThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btThem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btThem.TextMarginLeft = 0;
            this.btThem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btThem.UseDefaultRadiusAndThickness = true;
            this.btThem.Click += new System.EventHandler(this.btThem_Click);
            // 
            // txtTendanhnhap
            // 
            this.txtTendanhnhap.AcceptsReturn = false;
            this.txtTendanhnhap.AcceptsTab = false;
            this.txtTendanhnhap.AnimationSpeed = 200;
            this.txtTendanhnhap.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTendanhnhap.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTendanhnhap.BackColor = System.Drawing.Color.Transparent;
            this.txtTendanhnhap.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTendanhnhap.BackgroundImage")));
            this.txtTendanhnhap.BorderColorActive = System.Drawing.Color.Indigo;
            this.txtTendanhnhap.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTendanhnhap.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTendanhnhap.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTendanhnhap.BorderRadius = 30;
            this.txtTendanhnhap.BorderThickness = 1;
            this.txtTendanhnhap.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTendanhnhap.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTendanhnhap.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtTendanhnhap.DefaultText = "";
            this.txtTendanhnhap.FillColor = System.Drawing.Color.Lavender;
            this.txtTendanhnhap.HideSelection = true;
            this.txtTendanhnhap.IconLeft = null;
            this.txtTendanhnhap.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTendanhnhap.IconPadding = 10;
            this.txtTendanhnhap.IconRight = null;
            this.txtTendanhnhap.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTendanhnhap.Lines = new string[0];
            this.txtTendanhnhap.Location = new System.Drawing.Point(331, 482);
            this.txtTendanhnhap.MaxLength = 32767;
            this.txtTendanhnhap.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTendanhnhap.Modified = false;
            this.txtTendanhnhap.Multiline = false;
            this.txtTendanhnhap.Name = "txtTendanhnhap";
            stateProperties5.BorderColor = System.Drawing.Color.Indigo;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTendanhnhap.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTendanhnhap.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTendanhnhap.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.Lavender;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTendanhnhap.OnIdleState = stateProperties8;
            this.txtTendanhnhap.Padding = new System.Windows.Forms.Padding(3);
            this.txtTendanhnhap.PasswordChar = '\0';
            this.txtTendanhnhap.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTendanhnhap.PlaceholderText = "";
            this.txtTendanhnhap.ReadOnly = false;
            this.txtTendanhnhap.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTendanhnhap.SelectedText = "";
            this.txtTendanhnhap.SelectionLength = 0;
            this.txtTendanhnhap.SelectionStart = 0;
            this.txtTendanhnhap.ShortcutsEnabled = true;
            this.txtTendanhnhap.Size = new System.Drawing.Size(271, 41);
            this.txtTendanhnhap.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTendanhnhap.TabIndex = 32;
            this.txtTendanhnhap.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTendanhnhap.TextMarginBottom = 0;
            this.txtTendanhnhap.TextMarginLeft = 3;
            this.txtTendanhnhap.TextMarginTop = 0;
            this.txtTendanhnhap.TextPlaceholder = "";
            this.txtTendanhnhap.UseSystemPasswordChar = false;
            this.txtTendanhnhap.WordWrap = true;
            // 
            // txtMatKhau
            // 
            this.txtMatKhau.AcceptsReturn = false;
            this.txtMatKhau.AcceptsTab = false;
            this.txtMatKhau.AnimationSpeed = 200;
            this.txtMatKhau.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMatKhau.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMatKhau.BackColor = System.Drawing.Color.Transparent;
            this.txtMatKhau.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMatKhau.BackgroundImage")));
            this.txtMatKhau.BorderColorActive = System.Drawing.Color.Indigo;
            this.txtMatKhau.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMatKhau.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMatKhau.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMatKhau.BorderRadius = 30;
            this.txtMatKhau.BorderThickness = 1;
            this.txtMatKhau.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMatKhau.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhau.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtMatKhau.DefaultText = "";
            this.txtMatKhau.FillColor = System.Drawing.Color.Lavender;
            this.txtMatKhau.HideSelection = true;
            this.txtMatKhau.IconLeft = null;
            this.txtMatKhau.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhau.IconPadding = 10;
            this.txtMatKhau.IconRight = null;
            this.txtMatKhau.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMatKhau.Lines = new string[0];
            this.txtMatKhau.Location = new System.Drawing.Point(331, 552);
            this.txtMatKhau.MaxLength = 32767;
            this.txtMatKhau.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMatKhau.Modified = false;
            this.txtMatKhau.Multiline = false;
            this.txtMatKhau.Name = "txtMatKhau";
            stateProperties9.BorderColor = System.Drawing.Color.Indigo;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhau.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMatKhau.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhau.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.Lavender;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMatKhau.OnIdleState = stateProperties12;
            this.txtMatKhau.Padding = new System.Windows.Forms.Padding(3);
            this.txtMatKhau.PasswordChar = '\0';
            this.txtMatKhau.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMatKhau.PlaceholderText = "";
            this.txtMatKhau.ReadOnly = false;
            this.txtMatKhau.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMatKhau.SelectedText = "";
            this.txtMatKhau.SelectionLength = 0;
            this.txtMatKhau.SelectionStart = 0;
            this.txtMatKhau.ShortcutsEnabled = true;
            this.txtMatKhau.Size = new System.Drawing.Size(271, 41);
            this.txtMatKhau.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMatKhau.TabIndex = 31;
            this.txtMatKhau.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMatKhau.TextMarginBottom = 0;
            this.txtMatKhau.TextMarginLeft = 3;
            this.txtMatKhau.TextMarginTop = 0;
            this.txtMatKhau.TextPlaceholder = "";
            this.txtMatKhau.UseSystemPasswordChar = false;
            this.txtMatKhau.WordWrap = true;
            // 
            // cboChucVu
            // 
            this.cboChucVu.BackColor = System.Drawing.Color.Lavender;
            this.cboChucVu.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cboChucVu.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.cboChucVu.FormattingEnabled = true;
            this.cboChucVu.Items.AddRange(new object[] {
            "Quản lý",
            "Nhân viên bán hàng",
            "Nhân viên kho"});
            this.cboChucVu.Location = new System.Drawing.Point(345, 416);
            this.cboChucVu.Name = "cboChucVu";
            this.cboChucVu.Size = new System.Drawing.Size(241, 31);
            this.cboChucVu.TabIndex = 26;
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 30;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.Lavender;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(333, 411);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.Lavender;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties16;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox1.PlaceholderText = "";
            this.bunifuTextBox1.ReadOnly = true;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(269, 41);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 30;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 0;
            this.bunifuTextBox1.TextPlaceholder = "";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // txtSDT
            // 
            this.txtSDT.AcceptsReturn = false;
            this.txtSDT.AcceptsTab = false;
            this.txtSDT.AnimationSpeed = 200;
            this.txtSDT.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSDT.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSDT.BackColor = System.Drawing.Color.Transparent;
            this.txtSDT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSDT.BackgroundImage")));
            this.txtSDT.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSDT.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSDT.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSDT.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSDT.BorderRadius = 30;
            this.txtSDT.BorderThickness = 1;
            this.txtSDT.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSDT.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtSDT.DefaultText = "";
            this.txtSDT.FillColor = System.Drawing.Color.Lavender;
            this.txtSDT.HideSelection = true;
            this.txtSDT.IconLeft = null;
            this.txtSDT.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.IconPadding = 10;
            this.txtSDT.IconRight = null;
            this.txtSDT.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSDT.Lines = new string[0];
            this.txtSDT.Location = new System.Drawing.Point(331, 336);
            this.txtSDT.MaxLength = 32767;
            this.txtSDT.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSDT.Modified = false;
            this.txtSDT.Multiline = false;
            this.txtSDT.Name = "txtSDT";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSDT.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.Lavender;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSDT.OnIdleState = stateProperties20;
            this.txtSDT.Padding = new System.Windows.Forms.Padding(3);
            this.txtSDT.PasswordChar = '\0';
            this.txtSDT.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSDT.PlaceholderText = "";
            this.txtSDT.ReadOnly = false;
            this.txtSDT.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSDT.SelectedText = "";
            this.txtSDT.SelectionLength = 0;
            this.txtSDT.SelectionStart = 0;
            this.txtSDT.ShortcutsEnabled = true;
            this.txtSDT.Size = new System.Drawing.Size(269, 41);
            this.txtSDT.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSDT.TabIndex = 29;
            this.txtSDT.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSDT.TextMarginBottom = 0;
            this.txtSDT.TextMarginLeft = 3;
            this.txtSDT.TextMarginTop = 0;
            this.txtSDT.TextPlaceholder = "";
            this.txtSDT.UseSystemPasswordChar = false;
            this.txtSDT.WordWrap = true;
            // 
            // txtTenNV
            // 
            this.txtTenNV.AcceptsReturn = false;
            this.txtTenNV.AcceptsTab = false;
            this.txtTenNV.AnimationSpeed = 200;
            this.txtTenNV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenNV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenNV.BackColor = System.Drawing.Color.Transparent;
            this.txtTenNV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenNV.BackgroundImage")));
            this.txtTenNV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenNV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenNV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenNV.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenNV.BorderRadius = 30;
            this.txtTenNV.BorderThickness = 1;
            this.txtTenNV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenNV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNV.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtTenNV.DefaultText = "";
            this.txtTenNV.FillColor = System.Drawing.Color.Lavender;
            this.txtTenNV.HideSelection = true;
            this.txtTenNV.IconLeft = null;
            this.txtTenNV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNV.IconPadding = 10;
            this.txtTenNV.IconRight = null;
            this.txtTenNV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNV.Lines = new string[0];
            this.txtTenNV.Location = new System.Drawing.Point(331, 257);
            this.txtTenNV.MaxLength = 32767;
            this.txtTenNV.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenNV.Modified = false;
            this.txtTenNV.Multiline = false;
            this.txtTenNV.Name = "txtTenNV";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNV.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenNV.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNV.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.Lavender;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNV.OnIdleState = stateProperties24;
            this.txtTenNV.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenNV.PasswordChar = '\0';
            this.txtTenNV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenNV.PlaceholderText = "";
            this.txtTenNV.ReadOnly = false;
            this.txtTenNV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenNV.SelectedText = "";
            this.txtTenNV.SelectionLength = 0;
            this.txtTenNV.SelectionStart = 0;
            this.txtTenNV.ShortcutsEnabled = true;
            this.txtTenNV.Size = new System.Drawing.Size(269, 41);
            this.txtTenNV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenNV.TabIndex = 28;
            this.txtTenNV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenNV.TextMarginBottom = 0;
            this.txtTenNV.TextMarginLeft = 3;
            this.txtTenNV.TextMarginTop = 0;
            this.txtTenNV.TextPlaceholder = "";
            this.txtTenNV.UseSystemPasswordChar = false;
            this.txtTenNV.WordWrap = true;
            // 
            // txtMaNV
            // 
            this.txtMaNV.AcceptsReturn = false;
            this.txtMaNV.AcceptsTab = false;
            this.txtMaNV.AnimationSpeed = 200;
            this.txtMaNV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaNV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaNV.BackColor = System.Drawing.Color.Transparent;
            this.txtMaNV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaNV.BackgroundImage")));
            this.txtMaNV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMaNV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMaNV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMaNV.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaNV.BorderRadius = 30;
            this.txtMaNV.BorderThickness = 1;
            this.txtMaNV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaNV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.txtMaNV.DefaultText = "";
            this.txtMaNV.FillColor = System.Drawing.Color.Lavender;
            this.txtMaNV.HideSelection = true;
            this.txtMaNV.IconLeft = null;
            this.txtMaNV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.IconPadding = 10;
            this.txtMaNV.IconRight = null;
            this.txtMaNV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaNV.Lines = new string[0];
            this.txtMaNV.Location = new System.Drawing.Point(331, 188);
            this.txtMaNV.MaxLength = 32767;
            this.txtMaNV.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMaNV.Modified = false;
            this.txtMaNV.Multiline = false;
            this.txtMaNV.Name = "txtMaNV";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMaNV.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.Lavender;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaNV.OnIdleState = stateProperties28;
            this.txtMaNV.Padding = new System.Windows.Forms.Padding(3);
            this.txtMaNV.PasswordChar = '\0';
            this.txtMaNV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaNV.PlaceholderText = "";
            this.txtMaNV.ReadOnly = false;
            this.txtMaNV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaNV.SelectedText = "";
            this.txtMaNV.SelectionLength = 0;
            this.txtMaNV.SelectionStart = 0;
            this.txtMaNV.ShortcutsEnabled = true;
            this.txtMaNV.Size = new System.Drawing.Size(271, 41);
            this.txtMaNV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMaNV.TabIndex = 27;
            this.txtMaNV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaNV.TextMarginBottom = 0;
            this.txtMaNV.TextMarginLeft = 3;
            this.txtMaNV.TextMarginTop = 0;
            this.txtMaNV.TextPlaceholder = "";
            this.txtMaNV.UseSystemPasswordChar = false;
            this.txtMaNV.WordWrap = true;
            // 
            // btUpdate
            // 
            this.btUpdate.AllowAnimations = true;
            this.btUpdate.AllowMouseEffects = true;
            this.btUpdate.AllowToggling = false;
            this.btUpdate.AnimationSpeed = 200;
            this.btUpdate.AutoGenerateColors = false;
            this.btUpdate.AutoRoundBorders = false;
            this.btUpdate.AutoSizeLeftIcon = true;
            this.btUpdate.AutoSizeRightIcon = true;
            this.btUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btUpdate.BackColor1 = System.Drawing.Color.Lavender;
            this.btUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btUpdate.BackgroundImage")));
            this.btUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btUpdate.ButtonText = "Cập nhật";
            this.btUpdate.ButtonTextMarginLeft = 0;
            this.btUpdate.ColorContrastOnClick = 45;
            this.btUpdate.ColorContrastOnHover = 45;
            this.btUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btUpdate.CustomizableEdges = borderEdges4;
            this.btUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btUpdate.Font = new System.Drawing.Font("Arial", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btUpdate.ForeColor = System.Drawing.Color.BlueViolet;
            this.btUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btUpdate.IconMarginLeft = 11;
            this.btUpdate.IconPadding = 10;
            this.btUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btUpdate.IconSize = 25;
            this.btUpdate.IdleBorderColor = System.Drawing.Color.Indigo;
            this.btUpdate.IdleBorderRadius = 40;
            this.btUpdate.IdleBorderThickness = 1;
            this.btUpdate.IdleFillColor = System.Drawing.Color.Lavender;
            this.btUpdate.IdleIconLeftImage = null;
            this.btUpdate.IdleIconRightImage = null;
            this.btUpdate.IndicateFocus = false;
            this.btUpdate.Location = new System.Drawing.Point(475, 640);
            this.btUpdate.Name = "btUpdate";
            this.btUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btUpdate.OnDisabledState.BorderRadius = 40;
            this.btUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btUpdate.OnDisabledState.BorderThickness = 1;
            this.btUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btUpdate.OnDisabledState.IconLeftImage = null;
            this.btUpdate.OnDisabledState.IconRightImage = null;
            this.btUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btUpdate.onHoverState.BorderRadius = 40;
            this.btUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btUpdate.onHoverState.BorderThickness = 1;
            this.btUpdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btUpdate.onHoverState.IconLeftImage = null;
            this.btUpdate.onHoverState.IconRightImage = null;
            this.btUpdate.OnIdleState.BorderColor = System.Drawing.Color.Indigo;
            this.btUpdate.OnIdleState.BorderRadius = 40;
            this.btUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btUpdate.OnIdleState.BorderThickness = 1;
            this.btUpdate.OnIdleState.FillColor = System.Drawing.Color.Lavender;
            this.btUpdate.OnIdleState.ForeColor = System.Drawing.Color.BlueViolet;
            this.btUpdate.OnIdleState.IconLeftImage = null;
            this.btUpdate.OnIdleState.IconRightImage = null;
            this.btUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btUpdate.OnPressedState.BorderRadius = 40;
            this.btUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btUpdate.OnPressedState.BorderThickness = 1;
            this.btUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btUpdate.OnPressedState.IconLeftImage = null;
            this.btUpdate.OnPressedState.IconRightImage = null;
            this.btUpdate.Size = new System.Drawing.Size(138, 39);
            this.btUpdate.TabIndex = 20;
            this.btUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btUpdate.TextMarginLeft = 0;
            this.btUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btUpdate.UseDefaultRadiusAndThickness = true;
            this.btUpdate.Click += new System.EventHandler(this.btUpdate_Click_1);
            // 
            // labelUpDate
            // 
            this.labelUpDate.AutoSize = true;
            this.labelUpDate.Font = new System.Drawing.Font("Segoe UI", 19.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.labelUpDate.Location = new System.Drawing.Point(52, 86);
            this.labelUpDate.Name = "labelUpDate";
            this.labelUpDate.Size = new System.Drawing.Size(347, 45);
            this.labelUpDate.TabIndex = 18;
            this.labelUpDate.Text = "Thông Tin Nhân Viên";
            // 
            // buttExit
            // 
            this.buttExit.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.buttExit.FlatAppearance.BorderSize = 3;
            this.buttExit.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Red;
            this.buttExit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttExit.Font = new System.Drawing.Font("Showcard Gothic", 9F);
            this.buttExit.ForeColor = System.Drawing.SystemColors.ActiveBorder;
            this.buttExit.Location = new System.Drawing.Point(23, 21);
            this.buttExit.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.buttExit.Name = "buttExit";
            this.buttExit.Size = new System.Drawing.Size(47, 33);
            this.buttExit.TabIndex = 11;
            this.buttExit.Text = " X";
            this.buttExit.UseVisualStyleBackColor = true;
            this.buttExit.Click += new System.EventHandler(this.buttExit_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label3.Location = new System.Drawing.Point(71, 562);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(83, 19);
            this.label3.TabIndex = 15;
            this.label3.Text = "Mật Khẩu";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label4.Location = new System.Drawing.Point(71, 494);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(130, 19);
            this.label4.TabIndex = 17;
            this.label4.Text = "Tên Đăng Nhập";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label5.Location = new System.Drawing.Point(71, 198);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(116, 19);
            this.label5.TabIndex = 19;
            this.label5.Text = "Mã Nhân Viên";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label7.Location = new System.Drawing.Point(71, 423);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(76, 19);
            this.label7.TabIndex = 22;
            this.label7.Text = "Chức vụ";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label6.Location = new System.Drawing.Point(71, 358);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(116, 19);
            this.label6.TabIndex = 24;
            this.label6.Text = "Số điện Thoại";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label2.Location = new System.Drawing.Point(71, 279);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(150, 19);
            this.label2.TabIndex = 13;
            this.label2.Text = "Họ Tên Nhân Viên";
            // 
            // FNhanVien
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1389, 770);
            this.Controls.Add(this.panelUpdate);
            this.Controls.Add(this.dgvNhanVien);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.btADD);
            this.Controls.Add(this.label12);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FNhanVien";
            this.Text = "FNhanVien";
            this.Load += new System.EventHandler(this.FNhanVien_Load);
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNhanVien)).EndInit();
            this.panelUpdate.ResumeLayout(false);
            this.panelUpdate.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label12;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btXoa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btADD;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvNhanVien;
        private Bunifu.UI.WinForms.BunifuShadowPanel panelUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btThem;
        private Bunifu.UI.WinForms.BunifuTextBox txtTendanhnhap;
        private Bunifu.UI.WinForms.BunifuTextBox txtMatKhau;
        private System.Windows.Forms.ComboBox cboChucVu;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuTextBox txtSDT;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenNV;
        private Bunifu.UI.WinForms.BunifuTextBox txtMaNV;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btUpdate;
        private System.Windows.Forms.Label labelUpDate;
        private System.Windows.Forms.Button buttExit;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label2;
    }
}